version: "3"
services:
  grafana:
    image: grafana/grafana:9.3.6
    depends_on:
      - prometheus
      - loki
      - tempo
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards/
    networks:
      - default

  prometheus:
    image: prom/prometheus:v2.42.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - default

  loki:
    image: grafana/loki:2.7.3
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    volumes:
      - loki_data:/loki
    networks:
      - default

  promtail:
    image: grafana/promtail:2.7.3
    depends_on:
      - loki
    command:
      - '-config.file=/etc/promtail/promtail.yaml'
    volumes:
      - ./promtail:/etc/promtail
      - tle_fetcher_logs:/tle-fetcher-logs
    networks:
      - default

  tempo:
    image: grafana/tempo:2.0.0
    command:
      - '-config.file=/etc/tempo.yaml'
    ports:
      - "14268:14268"  # jaeger ingest, Jaeger - Thrift HTTP
      - "14250:14250"  # Jaeger - GRPC
      - "4317:4317"    # OpenTelemetry gRPC
      - "4318:4318"    # OpenTelemetry HTTP
      - "3102:3100"    # tempo
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/data/tempo
    networks:
      - default

  tle-fetcher:
    image: qaware/tle-fetcher:1.0.0
    environment:
      - QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
    depends_on:
      - tempo
      - prometheus
      - promtail
    ports:
      - "8080:8080"
    volumes:
      - tle_fetcher_logs:/logs
    networks:
      - default

#  sky-map:
#    image: qaware/sky-map:1.0.0
#    depends_on:
#      - tempo
#      - prometheus
#      - promtail
#    ports:
#      - "8088:8088"
#    volumes:
#      - sky_map_logs:/logs
#    networks:
#      - default

volumes:
  tle_fetcher_logs: {}
  sky_map_logs: {}
  prometheus_data: {}
  loki_data: {}
  tempo_data: {}
  grafana_data: {}

networks:
  default:
    driver: bridge
